import fs from 'fs';
import path from 'path';

interface OpenApiSpec {
	openapi: string;
	info: {
		title: string;
		version: string;
		description: string;
	};
	servers: Array<{
		url: string;
	}>;
	tags: Array<{
		name: string;
	}>;
	paths: Record<string, any>;
	components: {
		schemas: Record<string, any>;
	};
}

const plugin = process.argv[2] || 'multivendorx';

const controllersDir = path.join(
	process.cwd(),
	`plugins/${plugin}/classes/RestAPI/Controllers`
);

const spec: OpenApiSpec = {
	openapi: '3.1.0',
	info: {
		title: `${plugin} REST API`,
		version: '1.0.0',
		description: `${plugin} autogenerated REST documentation`
	},
	servers: [
		{
			url: `https://example.com/wp-json/${plugin}/v1`
		}
	],
	tags: [],
	paths: {},
	components: {
		schemas: {}
	}
};

function scanDirectory(dir: string): string[] {
	const result: string[] = [];

	for (const file of fs.readdirSync(dir)) {
		const filePath = path.join(dir, file);

		if (fs.statSync(filePath).isDirectory()) {
			result.push(...scanDirectory(filePath));
		} else if (file.endsWith('.php')) {
			result.push(filePath);
		}
	}

	return result;
}

function parseController(filePath: string) {
	const content = fs.readFileSync(filePath, 'utf8');

	const controllerName = path.basename(filePath, '.php');

	spec.tags.push({
		name: controllerName
	});

	const routeRegex =
		/register_rest_route\s*\(\s*[^,]+,\s*['"]([^'"]+)['"]/g;

	let match;

	while ((match = routeRegex.exec(content)) !== null) {
		let route = match[1];

		route = route.replace(
			/\(\?P<([^>]+)>[^\)]+\)/g,
			'{$1}'
		);

		if (!route.startsWith('/')) {
			route = '/' + route;
		}

		spec.paths[route] = spec.paths[route] || {};

		spec.paths[route].get = {
			tags: [controllerName],
			summary: `${controllerName} endpoint`,
			description: `Auto-generated route from ${controllerName}`,
			responses: {
				'200': {
					description: 'Successful response'
				}
			}
		};
	}
}

for (const file of scanDirectory(controllersDir)) {
	parseController(file);
}

fs.writeFileSync(
	'openapi.json',
	JSON.stringify(spec, null, 2)
);

console.log('Generated openapi.json');
