export const dummyEnrollments = [
	{
		id: 1,
		customer_id: 1,
		customer_name: 'Amit Sharma',
		customer_email: 'amit.sharma@example.com',
		customer_url: '#',
		customer_img: '',
		order_id: 31,
		order_item_id: 1,
		learners_hub_id: 1,
		enrollment_date: '2026-05-12',
		status: 'enrolled',
		cohort_id: 1,
		cohort_name: 'Web Development Beginners',
		moodle_cohort_id: '1',
		course_name: 'HTML & CSS Fundamentals',
		course_id: 101,
		course_image: '',
	},
	{
		id: 2,
		customer_id: 2,
		customer_name: 'Priya Verma',
		customer_email: 'priya.verma@example.com',
		customer_url: '#',
		customer_img: '',
		order_id: 32,
		order_item_id: 2,
		learners_hub_id: 2,
		enrollment_date: '2026-05-13',
		status: 'unenrolled',
		group_id: 2,
		group_name: 'Frontend Masters Group',
		course_name: 'Advanced React Training',
		course_id: 102,
		course_image: '',
	},
	{
		id: 3,
		customer_id: 3,
		customer_name: 'Rahul Mehta',
		customer_email: 'rahul.mehta@example.com',
		customer_url: '#',
		customer_img: '',
		order_id: 33,
		order_item_id: 3,
		learners_hub_id: 3,
		enrollment_date: '2026-05-14',
		status: 'enrolled',
		cohort_id: 3,
		cohort_name: 'JavaScript Essentials',
		course_name: 'Modern JavaScript Bootcamp',
		course_id: 103,
		course_image: '',
	},
	{
		id: 4,
		customer_id: 4,
		customer_name: 'Sneha Kapoor',
		customer_email: 'sneha.kapoor@example.com',
		customer_url: '#',
		customer_img: '',
		order_id: 34,
		order_item_id: 4,
		learners_hub_id: 4,
		enrollment_date: '2026-05-15',
		status: 'enrolled',
		group_id: 4,
		group_name: 'Laravel Experts',
		course_name: 'PHP and Laravel Mastery',
		course_id: 104,
		course_image: '',
	},
	{
		id: 5,
		customer_id: 5,
		customer_name: 'Arjun Patel',
		customer_email: 'arjun.patel@example.com',
		customer_url: '#',
		customer_img: '',
		order_id: 35,
		order_item_id: 5,
		learners_hub_id: 5,
		enrollment_date: '2026-05-16',
		status: 'unenrolled',
		cohort_id: 5,
		cohort_name: 'WooCommerce Store Management',
		course_name: 'WooCommerce Expert Course',
		course_id: 105,
		course_image: '',
	},
	{
		id: 6,
		customer_id: 6,
		customer_name: 'Neha Reddy',
		customer_email: 'neha.reddy@example.com',
		customer_url: '#',
		customer_img: '',
		order_id: 36,
		order_item_id: 6,
		learners_hub_id: 6,
		enrollment_date: '2026-05-17',
		status: 'enrolled',
		group_id: 6,
		group_name: 'TypeScript Developers',
		course_name: 'Modern TypeScript Development',
		course_id: 106,
		course_image: '',
	},
	{
		id: 7,
		customer_id: 7,
		customer_name: 'Karan Malhotra',
		customer_email: 'karan.malhotra@example.com',
		customer_url: '#',
		customer_img: '',
		order_id: 37,
		order_item_id: 7,
		learners_hub_id: 7,
		enrollment_date: '2026-05-18',
		status: 'enrolled',
		cohort_id: 7,
		cohort_name: 'REST API Development',
		course_name: 'REST API Engineering',
		course_id: 107,
		course_image: '',
	},
	{
		id: 8,
		customer_id: 8,
		customer_name: 'Ananya Singh',
		customer_email: 'ananya.singh@example.com',
		customer_url: '#',
		customer_img: '',
		order_id: 38,
		order_item_id: 8,
		learners_hub_id: 8,
		enrollment_date: '2026-05-19',
		status: 'unenrolled',
		group_id: 8,
		group_name: 'Backend Engineers',
		course_name: 'Node.js Backend Architecture',
		course_id: 108,
		course_image: '',
	},
	{
		id: 9,
		customer_id: 9,
		customer_name: 'Vikram Joshi',
		customer_email: 'vikram.joshi@example.com',
		customer_url: '#',
		customer_img: '',
		order_id: 39,
		order_item_id: 9,
		learners_hub_id: 9,
		enrollment_date: '2026-05-20',
		status: 'enrolled',
		cohort_id: 9,
		cohort_name: 'Full Stack Developer Program',
		course_name: 'Full Stack Engineering',
		course_id: 109,
		course_image: '',
	},
	{
		id: 10,
		customer_id: 10,
		customer_name: 'Riya Choudhury',
		customer_email: 'riya.choudhury@example.com',
		customer_url: '#',
		customer_img: '',
		order_id: 40,
		order_item_id: 10,
		learners_hub_id: 10,
		enrollment_date: '2026-05-21',
		status: 'enrolled',
		group_id: 10,
		group_name: 'WordPress Professionals',
		course_name: 'WordPress Plugin Development',
		course_id: 110,
		course_image: '',
	},
];
