export const dummyWholesalecustomer = [
	{
		id: 1,
		customer: 'John Doe',
		email: 'john@example.com',
		status: 'Approved',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 2,
		customer: 'Sarah Williams',
		email: 'sarah@example.com',
		status: 'Rejected',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 3,
		customer: 'Michael Brown',
		email: 'michael@example.com',
		status: 'Pending',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 4,
		customer: 'Emily Johnson',
		email: 'emily@example.com',
		status: 'Approved',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 5,
		customer: 'David Miller',
		email: 'david@example.com',
		status: 'Approved',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 6,
		customer: 'Sophia Wilson',
		email: 'sophia@example.com',
		status: 'Refunded',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 7,
		customer: 'James Anderson',
		email: 'james@example.com',
		status: 'Rejected',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 8,
		customer: 'Olivia Taylor',
		email: 'olivia@example.com',
		status: 'Approved',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 9,
		customer: 'Daniel Thomas',
		email: 'daniel@example.com',
		status: 'Rejected',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 10,
		customer: 'Emma Martinez',
		email: 'emma@example.com',
		status: 'Pending',
		date: 'May 12, 2026',
		action: '#',
	},
];