import { QuoteRow } from "./quoteRequests";

export const dummyQuotes: QuoteRow[] = [
	{
		id: 1,
		order_id: '#1001',
		date: 'May 12, 2026',
		status: 'expired-quote',
		total: '$120.00',
		action: '#',
		customer_name: 'John Smith',
	},
	{
		id: 2,
		order_id: '#1002',
		date: 'May 12, 2026',
		status: 'new-quote-request',
		total: '$89.00',
		action: '#',
		customer_name: 'Emma Johnson',
	},
	{
		id: 3,
		order_id: '#1003',
		date: 'May 12, 2026',
		status: 'pending-quote',
		total: '$45.00',
		action: '#',
		customer_name: 'Michael Brown',
	},
	{
		id: 4,
		order_id: '#1004',
		date: 'May 12, 2026',
		status: 'expired-quote',
		total: '$220.00',
		action: '#',
		customer_name: 'Sophia Davis',
	},
	{
		id: 5,
		order_id: '#1005',
		date: 'May 12, 2026',
		status: 'accepted-quote',
		total: '$75.00',
		action: '#',
		customer_name: 'James Wilson',
	},
	{
		id: 6,
		order_id: '#1006',
		date: 'May 12, 2026',
		status: 'rejected-quote',
		total: '$60.00',
		action: '#',
		customer_name: 'Olivia Martinez',
	},
	{
		id: 7,
		order_id: '#1007',
		date: 'May 12, 2026',
		status: 'rejected-quote',
		total: '$150.00',
		action: '#',
		customer_name: 'William Anderson',
	},
	{
		id: 8,
		order_id: '#1008',
		date: 'May 12, 2026',
		status: 'expired-quote',
		total: '$310.00',
		action: '#',
		customer_name: 'Ava Thomas',
	},
	{
		id: 9,
		order_id: '#1009',
		date: 'May 12, 2026',
		status: 'new-quote-request',
		total: '$95.00',
		action: '#',
		customer_name: 'Benjamin Taylor',
	},
	{
		id: 10,
		order_id: '#1010',
		date: 'May 12, 2026',
		status: 'pending-quote',
		total: '$40.00',
		action: '#',
		customer_name: 'Charlotte Moore',
	},
];